server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: application-service
          uri: lb://application-service
          predicates:
            - Path=/api/v1/applications/**
        - id: approval-service
          uri: lb://approval-service
          predicates:
            - Path=/api/v1/approvals/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,gateway
  tracing:
    sampling:
      probability: 1.0
